clone_folder: c:\qreal
test: off

environment:
  global:
    MINGW: C:\Qt\Tools\mingw492_32
    QTDIR: C:\Qt\5.5\mingw492_32
  matrix:
    - PROJECT_FILE: qrealRobots.pro
    - PROJECT_FILE: qreal.pro
#   - PROJECT_FILE: qrealMinimal.pro

configuration:
  - debug
  - release

install:
  - set PATH=%QTDIR%\bin;%MINGW%\bin;%WINDIR%\system32;%WINDIR%;%WINDIR%\System32\WindowsPowerShell\v1.0\;
build_script:
  - qmake %PROJECT_FILE% -r -spec win32-g++ CONFIG+=%CONFIGURATION%
  - mingw32-make -j2
